import type { Metadata } from "next";
import { Geist, Geist_Mono, Yesteryear } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* [#71b07a] */}
        {/* -[#111111] */}
        <div className="flex justify-between  text-white p-8 border-rounded  ">
          <ul className="flex ">
            <li>
              <Link href="/" className="yesteryear-regular text-4xl">
              HG
              </Link>
            </li>
          </ul>  
          <ul className="flex space-x-9">
            <li>
              <Link href="#about" className=" tomorrow-extrabold font-bold text-xl">
              About
              </Link>
            </li>
            <li>
              <Link href="#contact" className="tomorrow-extrabold font-bold text-xl">
              Contact
              </Link>
            </li>
          </ul>  

        </div>
        {children}
      </body>
    </html>
  );
}
